### ISSUE TITLE
[solved] Tower Idle and Attack animation won't work.

### ISSUE THREAD

**Issue by TanatornJ** [HalfHumanGames/DwerveMods#1]
1.Steps to reproduce
- Change tower sprites 
2.Expected behavior
- Custom animation for spawn, Idle and Attack
3.Actual behavior
- Only spawn sprites work
4.Version number
- Game version 1.1.8
5.Operating system
- Windows

Solution
1.Fixing idle animations (Crossbow)
- change from "core right" to "core."
2. Fixing attack animation (Crossbow and Bear)
- change from "Attack" to "AttackLeft", "AttackRight", "AttackUp" and "AttackDown"

I'm not sure if this is proper method to fix the problem.

**Comment by snarlynarwhal** [comment]
Thanks for reporting this! Can you link to your mod on CurseForge or upload the zip for your mod? I will take a look and see if it is a bug or if the docs need more clarification. Let me offer some more context:

The sprite paths and animation names depend on how you design the animation. For example, the default crossbow core is top-down and has a single idle animation and a single attack animation. Therefore, the default setup only uses Core and Attack and the core just rotates to face its target.

Other turrets like the chakram turret have different sprites and animations for each direction (up, right/left, down) and therefore use Core[Direction] and Attack[Direction]. To clarify left is just right flipped for most turrets, so you don't need to specify CoreLeft and AttackLeft. But if the sprite changes as it rotates to show perspective, then you want to use this setup.

That being said, if anything does not work as intended, please let me know! Leave it open for now and I can close once I either fix the bug or clarify the docs :)

**Comment by TanatornJ** [comment]
Thank you for clarification. Here is the link. https://www.curseforge.com/dwerve/mods/druid-arsenal
As I mentioned earlier, 1st time I make the crossbow sprites without messing with TOML file. The spawn animation and the "base" Idle animation works but the "Coreright" doesn't replace the old sprites. Somehow, I change it to "Core", and it magically solved Idle animation problems. 
Same situation goes for attacking as well. The bear trap default was "attack" which somehow doesn't work properly so I change it to 4 direction attack instead (luckily there are codes from other towers lul)

Another thing I didn't mention is I tried to change "KnockbackAmount", "SlowAmount" and "SlowDuration" but those didn't work while other stats work (I change number of power stones required).  Also, it would be cool if I can change projectiles and icon sprite too but that's not a big deal. Thanks again!

**Comment by snarlynarwhal** [comment]
I investigated and found that this is in fact a bug! The next version 1.1.14+ will include a fix where the template file works as intended. Although your workaround will also still work just fine and not require any updates. Thanks again for the report! :)
